const CODEX_SKILLS = [
  'api-design',
  'article-writing',
  'backend-patterns',
  'brand-voice',
  'bun-runtime',
  'claude-api',
  'coding-standards',
  'content-engine',
  'crosspost',
  'deep-research',
  'dmux-workflows',
  'documentation-lookup',
  'e2e-testing',
  'eval-harness',
  'everything-claude-code',
  'exa-search',
  'fal-ai-media',
  'frontend-patterns',
  'frontend-slides',
  'investor-materials',
  'investor-outreach',
  'market-research',
  'mcp-server-patterns',
  'nextjs-turbopack',
  'security-review',
  'strategic-compact',
  'tdd-workflow',
  'verification-loop',
  'video-editing',
  'x-api',
];

const HIGH_SIGNAL_SKILLS = [
  'api-design',
  'backend-patterns',
  'coding-standards',
  'deep-research',
  'documentation-lookup',
  'e2e-testing',
  'eval-harness',
  'frontend-patterns',
  'mcp-server-patterns',
  'security-review',
  'strategic-compact',
  'tdd-workflow',
  'verification-loop',
];

const OPENCODE_INSTRUCTION_SKILLS = [
  'tdd-workflow',
  'security-review',
  'coding-standards',
  'frontend-patterns',
  'backend-patterns',
  'e2e-testing',
  'verification-loop',
  'api-design',
  'strategic-compact',
  'eval-harness',
  'documentation-lookup',
  'mcp-server-patterns',
  'deep-research',
];

module.exports = {
  CODEX_SKILLS,
  HIGH_SIGNAL_SKILLS,
  OPENCODE_INSTRUCTION_SKILLS,
};
